// <auto-generated />
using System;
using GladiusShip.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GladiusShip.Infrastructure.Migrations
{
    [DbContext(typeof(GladiusShipContext))]
    [Migration("20260326133408_Expertise")]
    partial class Expertise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.Expertise", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Ref");

                    b.ToTable("Expertise");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.Insurance", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PersonalRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref");

                    b.ToTable("Insurance");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.InsuranceDetails", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Ref");

                    b.ToTable("InsuranceDetails");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.Log", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ref");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.Maintenance", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PersonalRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref");

                    b.ToTable("Maintenance");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.MaintenanceDetails", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<Guid>("MaintenanceRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref");

                    b.ToTable("MaintenanceDetails");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.MaintenanceJob", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<DateTime>("JobDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PersonalRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponsiblePersonal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Ref");

                    b.ToTable("MaintenanceJob");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.MaintenanceJobAction", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MasterComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NextActionHour")
                        .HasColumnType("int");

                    b.HasKey("Ref");

                    b.ToTable("MaintenanceJobAction");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.MaintenanceJobCost", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PartCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Ref");

                    b.ToTable("MaintenanceJobCost");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.MaintenanceJobItem", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<Guid>("JobRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarrantyFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ref");

                    b.ToTable("MaintenanceJobItem");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.MaintenanceJobPhoto", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ref");

                    b.ToTable("MaintenanceJobPhoto");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.MaintenanceJobRisk", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EngineHourAfter")
                        .HasColumnType("int");

                    b.Property<int?>("EngineHourBefore")
                        .HasColumnType("int");

                    b.Property<bool>("HasWaste")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WasteDetail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ref");

                    b.ToTable("MaintenanceJobRisk");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.Marina", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref");

                    b.ToTable("Marina");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.MarinaDetails", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<Guid>("MarinaRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref");

                    b.ToTable("MarinaDetails");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.MarinaPermission", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<Guid>("PortRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Ref");

                    b.ToTable("MarinaPermission");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.MarinaPrice", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MarinaRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Ref");

                    b.ToTable("MarinaPrice");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.MarinaRoad", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<Guid>("PortRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Ref");

                    b.ToTable("MarinaRoad");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.Port", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ref");

                    b.ToTable("Port");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.Role", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ref");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.RoleDetail", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref");

                    b.ToTable("RoleDetails", (string)null);
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.Ship", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HullId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ref");

                    b.ToTable("Ship");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.ShipDocument", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CEDocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MMSINumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PermitValidity")
                        .HasColumnType("datetime2");

                    b.Property<string>("RadioCallSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("İnsuranceExpire")
                        .HasColumnType("datetime2");

                    b.HasKey("Ref");

                    b.ToTable("ShipDocument");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.ShipMachine", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EngineClock")
                        .HasColumnType("int");

                    b.Property<string>("MachineBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineSerial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref");

                    b.ToTable("ShipMachine");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.ShipPermission", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonalRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref");

                    b.ToTable("ShipPermission");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.ShipPhoto", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref");

                    b.ToTable("ShipPhoto");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.ShipRegistration", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GrossTonilato")
                        .HasColumnType("int");

                    b.Property<Guid>("PortRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationSize")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationWidth")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShipCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref");

                    b.ToTable("ShipRegistration");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.User", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ref");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
