// <auto-generated />
using System;
using GladiusShip.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GladiusShip.Infrastructure.Migrations
{
    [DbContext(typeof(GladiusShipContext))]
    [Migration("20260225072126_ShipTableCustomerRef")]
    partial class ShipTableCustomerRef
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.Log", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ref");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.Role", b =>
                {
                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Ref")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.RoleDetail", b =>
                {
                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleRef")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("RoleDetails");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.Ship", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HullId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ref");

                    b.ToTable("Ship");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.ShipDocument", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CEDocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MMSINumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PermitValidity")
                        .HasColumnType("datetime2");

                    b.Property<string>("RadioCallSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("İnsuranceExpire")
                        .HasColumnType("datetime2");

                    b.HasKey("Ref");

                    b.ToTable("ShipDocument");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.ShipMachine", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EngineClock")
                        .HasColumnType("int");

                    b.Property<string>("MachineBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineSerial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref");

                    b.ToTable("ShipMachine");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.ShipPhoto", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref");

                    b.ToTable("ShipPhoto");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.ShipRegistration", b =>
                {
                    b.Property<Guid>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GrossTonilato")
                        .HasColumnType("int");

                    b.Property<Guid>("PortRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationSize")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationWidth")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShipCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ShipRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ref");

                    b.ToTable("ShipRegistration");
                });

            modelBuilder.Entity("GladiusShip.Infrastructure.Entity.User", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsPassive")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
